image: alpine:latest

deploy:
  stage: deploy
  tags: 
    - deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY_DEV" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $HOST_DEV >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER_DEV@$HOST_DEV "./deploy-lib-jitsi-meet.sh"
  artifacts:
    paths:
    - public
  only:
  - lag-dev
